# Declare dotfiles not generated by Nix options.

{ config, lib, pkgs, ... }:

let
  dotfiles = ./dotfiles;
  onPerscitia = config.networking.hostName == "perscitia";
in
{
  home-manager.users.tmplt.home.file = lib.mkIf onPerscitia {
    ".config/mpv/scripts/youtube-quality.lua".source = "${dotfiles}/mpv/.config/mpv/scripts/youtube-quality.lua";
    ".config/mpv/scripts/youtube-quality.conf".source = "${dotfiles}/mpv/.config/mpv/scripts/youtube-quality.conf";

    ".config/nvim".source = "${dotfiles}/vim/.config/nvim";
    ".irssi".source = "${dotfiles}/irssi/.irssi";
    ".vimrc".source = "${dotfiles}/vim/.vimrc";
    ".xmobarrc".source = "${dotfiles}/xmonad/.xmobarrc";
    ".Xresources".source = "${dotfiles}/xfiles/.Xresources";
    ".zimrc".source = "${dotfiles}/zsh/.zimrc";
    ".zsh".source = "${dotfiles}/zsh/.zsh";
    ".zshrc".source = "${dotfiles}/zsh/.zshrc";
  };
}
