# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/376d2c4d-0a78-4f68-a75f-a475b334ed6b";
      fsType = "ext4";
    };

  fileSystems."/media" =
    { device = "main/media";
      fsType = "zfs";
    };

  fileSystems."/volatile" =
    { device = "volatile";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d5255f7f-237a-4633-8875-3a4c8355e725"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
